version: '3.8'
services:
  service-a:
    build:
      context: ./services/service-a
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/service-a:/app  
      - /app/node_modules      
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-a-db
      - rabbitmq

  service-b:
    build:
      context: ./services/service-b
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/service-b:/app  
      - /app/node_modules         
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-b-db
      - rabbitmq

  service-a-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_a
    ports:
      - "5433:5432"  
      
  service-b-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_b
    ports:
      - "5434:5432"   

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    name: microservices_network
    external: true
