version: '3.8'
services:
  service-a:
    build:
      context: ./services/service-a
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/service-a:/app  
      - /app/node_modules      
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-a-db
      - rabbitmq
      - otel-collector

  service-b:
    build:
      context: ./services/service-b
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/service-b:/app  
      - /app/node_modules         
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-b-db
      - rabbitmq

  service-a-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_a
    ports:
      - "5433:5432"  
      
  service-b-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_b
    ports:
      - "5434:5432"   

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  otel-collector:
      image: otel/opentelemetry-collector-contrib:latest
      volumes:
        - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      command:
        - "--config=/etc/otel-collector-config.yml"
      ports:
        - "4317:4317"  # Porta para OTLP gRPC
        - "4318:4318"  # Porta para OTLP HTTP

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'  # Interface do Jaeger
      - '4319:4317'  # Porta de coleta de traços    

networks:
  default:
    name: microservices_network
    external: true
