apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-a-db
spec:
  serviceName: service-a-db-postgres
  replicas: 2
  selector:
    matchLabels:
      app: service-a-db
  template:
    metadata:
      labels:
        app: service-a-db
    spec:
      containers:
      - name: service-a-db
        image: postgres:13
        ports:
        - containerPort: 5432

        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - postgres
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
          timeoutSeconds: 5 

        envFrom:
        - secretRef:
            name: secret-service-a-db
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-volume    

  volumeClaimTemplates:
    - metadata:
        name: postgres-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]          
        resources:
          requests:
            storage: 1Gi  
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-db-postgres
spec:
  selector:
    app: service-a-db
  ports:
    - port: 5432
  clusterIP: None
