apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a-db
  template:
    metadata:
      labels:
        app: service-a-db
    spec:
      containers:
      - name: service-a-db
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: service-a-db-env

---
apiVersion: v1
kind: Service
metadata:
  name: service-a-db
spec:
  ports:
    - port: 5432
  selector:
    app: service-a-db
  type: ClusterIP
