apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: adson14/service-a:v1.1
        ports:
        - containerPort: 3001

        startupProbe: #Verifica a inicialização do container
          httpGet:
            path: /healthz
            port: 3001
          periodSeconds: 5 # Intervalo de verificação
          failureThreshold: 10 # Quantidade de falhas    

        readinessProbe: #Controla o recebimento de trafego removendo o container do load balancer em caso de falha
          httpGet:
            path: /healthz
            port: 3001
          failureThreshold: 10
          periodSeconds: 20

        livenessProbe: # verifica a saúde do container, caso contrario, o container será reiniciado
          httpGet:
            path: /healthz
            port: 3001
          periodSeconds: 20
          failureThreshold: 1 # Após 1 falhas, o container será reiniciado
          timeoutSeconds: 3 # Tempo limite para a aplicação responder
          successThreshold: 1 # Quantidade de sucessos para considerar o container saudável

        envFrom:
        - configMapRef:
            name: service-a-env
        - secretRef:
            name: secret-service-a    

---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
  type: LoadBalancer
