apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b-db
  template:
    metadata:
      labels:
        app: service-b-db
    spec:
      containers:
      - name: service-b-db
        image: postgres:13
        ports:
        - containerPort: 5432

        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - postgres
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
          timeoutSeconds: 5

        envFrom:
        - secretRef:
            name: secret-service-b-db

---
apiVersion: v1
kind: Service
metadata:
  name: service-b-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: service-b-db
  type: ClusterIP
