apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: adson14/service-b:v1.1
        ports:
        - containerPort: 3002

        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"


        startupProbe: #Verifica a inicialização do container
          httpGet:
            path: /healthz
            port: 3002
          periodSeconds: 5 # Intervalo de verificação
          failureThreshold: 10 # Quantidade de falhas    

        readinessProbe: #Controla o recebimento de trafego removendo o container do load balancer em caso de falha
          httpGet:
            path: /healthz
            port: 3002
          failureThreshold: 10
          periodSeconds: 20

        livenessProbe: # verifica a saúde do container, caso contrario, o container será reiniciado
          httpGet:
            path: /healthz
            port: 3002
          periodSeconds: 20
          failureThreshold: 1 # Após 1 falhas, o container será reiniciado
          timeoutSeconds: 3 # Tempo limite para a aplicação responder
          successThreshold: 1 # Quantidade de sucessos para considerar o container saudável

        envFrom:
        - configMapRef:
            name: service-b-env
        - secretRef:
            name: secret-service-b    

---
apiVersion: v1
kind: Service
metadata:
  name: service-b-service
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 3002
  type: LoadBalancer
